#' Example Expression Matrix for H. sapiens
#'
#' Expression matrix with normalized values.
#'
#' @format Matrix with rows representing genes and columns representing samples.
#' @source GEO - GSE54152

"example_matrix"

#' Example Expression Matrix for M. musculus
#'
#' Expression matrix with normalized values.
#'
#' @format Matrix with rows representing genes and columns representing samples.
#' @source GEO - GSE126629 and GSE132214

"example_matrix_Mm"

#' Example Gene List for H.sapiens
#'
#' List of genes.
#'
#' @format List
#' @source generated for the example

"example_genes"

#' Example Network for H. sapiens
#'
#' Network computed from the example expression matrix of H. sapiens.
#'
#' @format Network
#' @source generated by ARACNe

"example_network"

#' Regulon computed from A549 cells
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"tumoral_regulon"

#' Regulon computed from hESC h9 line
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"neural_regulon"

#' Regulon computed from HEK293T cells treated with interferon
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"interferon_regulon"

#' Regulon computed from M. musculus neurons and whole brain
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"mouse_neuronal_regulon"

#' H. sapiens Regulators List
#'
#' List of known regulators.
#'
#' @format List
#' @source Gene Ontology

"regulators_list"

#' M. musculus Regulators List
#'
#' List of known regulators.
#'
#' @format List
#' @source Gene Ontology

"regulators_list_Mm"
