#' Example Expression Matrix
#'
#' Expression matrix with normalized values of a H. Sapiens dataset.
#'
#' @format Matrix with rows representing genes and columns representing samples.
#' @source GEO - GSE54152

"vsd_matrix"

#' Example Data Frame
#'
#' Data frame obtained from the network computed from the expression matrix.
#'
#' @format Data frame
#' \describe{
#'   \item{from}{Character, gene ID}
#'   \item{to}{Character, gene ID}
#'   \item{weight}{Numeric, weight of the edge}
#' }
#' @source generated from the example expression matrix

"network_df"

#' Example Regulators List
#'
#' List of ADAR regulators.
#'
#' @format List
#' @source generated for the example

"regulators_list"

#' Example Network
#'
#' Data frame obtained from the network computed from the expression matrix.
#'
#' @format Network
#' @source generated by ARACNe

"network"

#' Regulon computed from A549 cells
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"regul_A549_cells"

#' Regulon computed from hESC h9 line
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"regul_hESC_neurons"

#' Regulon computed from HEK293T cells treated with interferon
#'
#' Object of class "regulon".
#'
#' @format Regulon
#' @source computed from the dataset

"regul_interferon_specific"
